# Generated by Django 4.2.19 on 2025-03-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('shopify_auction_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('auction_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auctions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuctionProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=255)),
                ('winning_cusotmer', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'auction_relation_with_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BidRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('auction_shopify_id', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bidding_datetime', models.DateTimeField()),
                ('bid_type', models.CharField(max_length=50)),
                ('user_city', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'bid_records',
                'managed': False,
            },
        ),
    ]
